url: http://deadlybossmods.github.io
title: DeadlyBossMods
permalink: pretty
baseurl: ""
twitter_username: deadlybossmods
github_username: DeadlyBossMods
exclude:
  - .editconfig
  - .ruby-version
  - Dangerfile
  - Gemfile
  - LICENSE
  - Rakefile
sass:
  style: compressed
lunr_search:
  js_dir: "assets/js"
plugins:
  - jekyll-lunr-js-search
  - jekyll-seo-tag
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
